CREATE TABLE tblusers (
	id SERIAL NOT NULL PRIMARY KEY,
	email VARCHAR(120) UNIQUE NOT NULL,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50),	
	phone VARCHAR(15),
	password TEXT,
	country TEXT,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE tblroles(
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- CREATE TABLE tbluser_roles(
-- 	id SERIAL NOT NULL PRIMARY KEY,
-- 	user_id INTEGER NOT NULL REFERENCES tblusers(id),
-- 	role_id INTEGER NOT NULL REFERENCES tblroles(id) 
-- );
ALTER TABLE tbluser_roles RENAME COLUMN role_iid TO role_id;
-- user_id INTEGER NOT NULL REFERENCES tbluser(id),
CREATE TABLE tblproduits (
	id SERIAL NOT NULL PRIMARY KEY,
	label VARCHAR(50) NOT NULL,	
	description TEXT ,
	pu INTEGER ,
	qte INTEGER NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tblcommandes(
	id SERIAL NOT NULL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES tblusers(id),
	status VARCHAR(10) NOT NULL DEFAULT 'Pending',
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE tblproduit_commandes(
	id SERIAL NOT NULL PRIMARY KEY,
	produit_id INTEGER NOT NULL REFERENCES tblproduits(id),
	commande_id INTEGER NOT NULL REFERENCES tblcommandes(id),
	qte_cmd INTEGER NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE tblexpeditions (id SERIAL NOT NULL PRIMARY KEY,
	adresse_livraison VARCHAR(100) NOT NULL,
	status_expedition VARCHAR(10) NOT NULL DEFAULT 'Pending',
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE tblexpedition_commandes (
	id SERIAL NOT NULL PRIMARY KEY,
	commande_id INTEGER NOT NULL REFERENCES tblcommandes(id),
	expedition_id INTEGER NOT NULL REFERENCES tblexpeditions(id),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);